CitcWeb/Controllers/CourseSchedulesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CitcWeb.Domain;
using CitcWeb.Services;
using CitcWeb.Services.Interface;
using PagedList;

namespace CitcWeb.Controllers
{
    public class CourseSchedulesController : Controller
    {
        private readonly IClassInfoService _classService;
        private readonly ICourseScheduleService _courseScheduleService;
        private readonly ISelectListService _selectListService;

        public CourseSchedulesController(IClassInfoService classService, ICourseScheduleService courseScheduleService, ISelectListService selectListService)
        {
            _classService = classService;
            _courseScheduleService = courseScheduleService;
            _selectListService = selectListService;
        }

        // GET: CourseSchedules
        public ActionResult Index(int classSn)
        {
            var courseSchedules = _courseScheduleService.Get(classSn);

            return View(courseSchedules);
        }
        public ActionResult ClassIndex(string className, int page = 1)
        {
            ViewBag.className = className;
            IEnumerable<ClassInfo> classInfo;
            if (string.IsNullOrWhiteSpace(className))
            {
                classInfo = _classService.Get();
            }
            else
            {
                classInfo = _classService.Get(className);
            }

            return View(classInfo.ToPagedList(page, 20));
        }


        // GET: CourseSchedules/Create
        public ActionResult Create(DateTime date,int lesson,int classSn)
        {
            PrepareSelectList(classSn);
            return View(new CourseSchedule {Date = date,LessonStart = lesson,LessonEnd = lesson,ClassSn = classSn});
        }

        private void PrepareSelectList(int classSn)
        {
            ViewBag.CourseSn = _selectListService.GetLeftCourse(classSn);
            ViewBag.TeacherSn = _selectListService.GetTeacher();
            ViewBag.LessonStart = _selectListService.GetLessonStartEnd();
            ViewBag.LessonEnd = _selectListService.GetLessonStartEnd();
        }

        // POST: CourseSchedules/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Sn,Date,LessonStart,LessonEnd,Location,ClassSn,CourseSn,TeacherSn,OtherEvent,confirmError")] CourseSchedule courseSchedule,bool confirmError=false)
        {
            if (ModelState.IsValid)
            {
                var result = _courseScheduleService.Add(courseSchedule,confirmError);
                if (result == null)
                {
                    return Redirect($"/CourseSchedules/Index?classSn={courseSchedule.ClassSn}#{courseSchedule.Date:MM/dd}");
                }
                else if (result.Contains("本月上課時數將會超過16小時"))
                {
                    ViewBag.teacherError = result;
                }
                else
                {
                    ViewBag.addResult = result;
                }

            }
            PrepareSelectList(courseSchedule.ClassSn);
            return View(courseSchedule);
        }
        public ActionResult Delete(int Sn)
        {
            var dateTime = _courseScheduleService.Delete(Sn);
            return Redirect(Request.UrlReferrer?.ToString()+$"#{dateTime:MM/dd}");
        }



    }
}

CitcWeb/Views/CourseSchedules/ClassIndex.cshtml
@using PagedList.Mvc;
@using PagedList;
@model IEnumerable<CitcWeb.Domain.ClassInfo>

@{
    ViewBag.Title = "班隊課表檢索";
}

<h2 id="pageTitle">班隊課表檢索 <i id="titleIcon" class="fa fa-toggle-down"></i></h2>
<div id="searchDiv" class="jumbotron">
    @using (Html.BeginForm("ClassIndex", "CourseSchedules", FormMethod.Post))
    {
        <div class="form-inline">
            <span>班隊名稱：</span> @Html.TextBox("className", null, new { @class = "form-control" })
            <input type="submit" value="搜尋" class="col- btn btn-primary offset-md-1" />
        </div>
    }
</div>
@Html.PagedListPager((IPagedList)Model,x=>Url.Action("ClassIndex",new { page=x,className=ViewBag.className}))
@foreach (var item in Model)
{
    <a href="/CourseSchedules/Index?classSn=@(item.Sn)#week@((DateTime.Now-item.StartDate).Days/7+1)" class="btn btn-outline-dark col-md-5" target="_blank">
        @Html.DisplayFor(modelItem => item.ClassName)
    </a>   
}

@section styles{
    <link href="~/Content/searchPage.css" rel="stylesheet" />
    <link href="~/Content/table.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Scripts/searchPage.js"></script>
}

CitcWeb/Views/CourseSchedules/Close.cshtml
@{
    Layout = null;
}

    <script>
        window.close();
    </script>

CitcWeb/Views/CourseSchedules/Create.cshtml
@model CitcWeb.Domain.CourseSchedule

@{
    ViewBag.Title = "排課";
}

<h2>排課</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @if (ViewBag.addResult!=null) { 
            <div class="alert alert-danger">
                @ViewBag.addResult
            </div>
        
        }
        @if (ViewBag.teacherError!=null) { 
            <div class="alert alert-danger">
                @ViewBag.teacherError
                @Html.Hidden("confirmError",true);
            </div>
        
        }
        <div class="form-group">
            上課日期
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            開始上課節數
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.LessonStart, new { htmlAttributes = new { @class = "form-control", @required = "required" } })*@
                @Html.DropDownListFor(model => model.LessonStart, null,"請選擇", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LessonStart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            結束上課節數
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.LessonEnd, null,"請選擇", htmlAttributes: new { @class = "form-control" })
                @*@Html.EditorFor(model => model.LessonEnd, new { htmlAttributes = new { @class = "form-control", @required = "required" } })*@
                @Html.ValidationMessageFor(model => model.LessonEnd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            上課地點
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.Location, "必須要填寫上課地點", new { @class = "text-danger" })
            </div>
        </div>

        <div class="leftDiv alert alert-secondary" style="min-width:400px">
<h4>非一般課程</h4>
        <div class="form-group">
            其他事件
            <div class="col-md-10">
                @Html.EditorFor(model => model.OtherEvent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OtherEvent, "", new { @class = "text-danger" })
            </div>
        </div>

        </div>

<div class="leftDiv alert alert-danger"  style="min-width:400px">

<h4>一般課程</h4>
                @Html.HiddenFor(model => model.ClassSn)
        <div class="form-group">
            課程
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CourseSn, null,"請選擇", htmlAttributes: new { @class = "form-control"  })
                @Html.ValidationMessageFor(model => model.CourseSn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            教官
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TeacherSn, null,"請選擇", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TeacherSn, "", new { @class = "text-danger" })
            </div>
        </div>

</div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@section styles{
    <link href="~/Content/select2.min.css" rel="stylesheet" />
    <style>
        .leftDiv {
            display: table-cell;
            /*vertical-align: middle;*/
            float: none;
            padding: 0 0 0 0;
        }
    </style>
}
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryUI")
}

CitcWeb/Views/CourseSchedules/Index.cshtml
@model List<CitcWeb.Models.CourseScheduleModel>

@{
    Layout = null;
    Dictionary<int, int> currentCourseHourLookup = new Dictionary<int, int>();
}

@helper GetDayOfWeek(DayOfWeek dayOfWeek){
switch(dayOfWeek)
{
    case DayOfWeek.Monday:
        <span>星期一</span>
        break;
    case DayOfWeek.Tuesday:
        <span>星期二</span>
        break;
    case DayOfWeek.Wednesday:
        <span>星期三</span>
        break;
    case DayOfWeek.Thursday:
        <span>星期四</span>
        break;
    case DayOfWeek.Friday:
        <span>星期五</span>
        break;
    case DayOfWeek.Saturday:
        <span>星期六</span>
        break;
    case DayOfWeek.Sunday:
        <span>星期日</span>
        break;

}
}

            <!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>課表</title>
    @Styles.Render("~/Content/css")
</head>

<br />

@foreach(var item in Model)
{
<table id="week@(item.Week)" width="95%" align="center">
    <tr><td colspan="13" style="font-size:x-large">軍事情報學校@(item.ClassName)第 @(item.Week) 週教育課程表</td></tr>
    <tr><td colspan="2">節次</td><td width="8%">0</td><td width="8%">1</td><td width="8%">2</td><td width="8%">3</td><td width="8%">4</td><td width="8%">5</td><td width="8%">6</td><td width="8%">7</td><td width="8%">8</td><td width="8%">晚自習(一)</td><td width="8%">晚自習(二)</td></tr>
    <tr>
        <td colspan="2"><div>時間<br />課程<br />日期</div></td>
        @if (item.Month > 4 && item.Month < 11)
        {
            <td>0530<br />|<br />0750</td> <td>0800<br />|<br />0850</td> <td>0900<br />|<br />0950</td> <td>1000<br />|<br />1050</td> <td>1100<br />|<br />1150</td> <td>1400<br />|<br />1450</td> <td>1500<br />|<br />1550</td> <td>1600<br />|<br />1650</td> <td>1630<br />|<br />1720</td> <td>1930<br />|<br />2020</td> <td>2030<br />|<br />2130</td>
        }
        else
            {
            <td>0600<br />|<br />0750</td> <td>0800<br />|<br />0850</td> <td>0900<br />|<br />0950</td> <td>1000<br />|<br />1050</td> <td>1100<br />|<br />1150</td> <td>1330<br />|<br />1420</td> <td>1430<br />|<br />1520</td> <td>1530<br />|<br />1620</td> <td>1630<br />|<br />1720</td> <td>1930<br />|<br />2020</td> <td>2030<br />|<br />2130</td>
        }
    </tr>
    @foreach (var day in item.CourseSchedules.Select(x => x.Date).Distinct()) {
        <tr>
            <td id="@day.ToString("MM/dd")"><br />@day.ToString("MM/dd") <br />@GetDayOfWeek(day.DayOfWeek)</td><td><p>課目</p><p>時數</p><p>教官</p><p style="border-bottom:unset">地點</p></td>
            @foreach( var schedule in item.CourseSchedules.Where(x=>x.Date==day)){
                    if (schedule.Course == null)
                    {
                    <td colspan="@(schedule.LessonEnd - schedule.LessonStart + 1)">
                            @if (schedule.OtherEvent == "未排課")
                                {
                                <a class="newCourseLink" href="/CourseSchedules/Create?date=@(schedule.Date.ToShortDateString())&lesson=@(schedule.LessonStart)&classSn=@(item.ClassSn)">
                                    <span style="font-size:x-large">@schedule.OtherEvent</span>
                                </a>
                            }
                            else if (schedule.LessonEnd - schedule.LessonStart > 0)
                            {
                                <a href="/CourseSchedules/Delete?Sn=@(schedule.Sn)" onclick="return confirm('確定要刪除嗎？')">
                                    <span style="font-size:x-large">@schedule.OtherEvent</span>
                                </a>
                            }
                            else 
                            {
                                <a href="/CourseSchedules/Delete?Sn=@(schedule.Sn)" onclick="return confirm('確定要刪除嗎？')">
                                    <p>@schedule.OtherEvent</p>
                                    <p style="border-bottom:unset">@schedule.Location</p>
                                </a>
                            }
                    </td>
                    }
                    else
                    {
                    <td colspan="@(schedule.LessonEnd - schedule.LessonStart + 1)">
                          @{
                            if (!currentCourseHourLookup.ContainsKey(schedule.CourseSn.Value))
                            {
                                currentCourseHourLookup[schedule.CourseSn.Value] = 0;
                            }
                            currentCourseHourLookup[schedule.CourseSn.Value] = currentCourseHourLookup[schedule.CourseSn.Value] + schedule.LessonEnd - schedule.LessonStart + 1;
                        }
                                <a href="/CourseSchedules/Delete?Sn=@(schedule.Sn)" onclick="return confirm('確定要刪除嗎？')">
                                    <p>@schedule.Course.Name</p>
                                    <p>@(currentCourseHourLookup[schedule.CourseSn.Value])/@(item.CourseHourLookup[schedule.CourseSn.Value])</p>
                                    <p>@schedule.Teacher.Name</p>
                                    <p style="border-bottom:unset">@schedule.Location</p>
                        </td>
                    }
                }


        </tr>
    }
    <tr><td>附記</td><td colspan="12" height="150px"></td></tr>
    <tr><td colspan="4">核轉主官意見</td><td colspan="4">中隊部</td><td colspan="5">批示</td></tr>
    <tr><td colspan="4" height="350px">請核示。</td><td colspan="4"></td><td colspan="5"></td></tr>


</table>
    <p style="page-break-after:always"></p>
}

<style>
    td{
        text-align:center; 
        border:solid 1px black;
        border-collapse:collapse;
        border-spacing:0;
        font-family:DFKai-SB;
    }
    p{
        margin:0 0 0 0 ;
        border-bottom:solid 1px black;
    }
    a{
        /*color:black;*/
        text-decoration:none;
    }
    a:hover{
        text-decoration:none;
    }
    @@page{
        margin:0.5cm;
    }
    @@media print{
        a:link,a:visited,a{
            text-decoration:none;
            color:black;
        }
    }

</style>