CitcWeb/Controllers/StudentReportsController.cs
using System;
using System.IO;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CitcWeb.Domain;
using CitcWeb.Services.Interface;
using PagedList;

namespace CitcWeb.Controllers
{
    public class StudentReportsController : Controller
    {
        private readonly IStudentReportService _studentReportService;
        private readonly ISelectListService _selectListService;

        public StudentReportsController(IStudentReportService studentReportService, ISelectListService selectListService)
        {
            _studentReportService = studentReportService;
            _selectListService = selectListService;
        }

        // GET: StudentReports
        public ActionResult Index(string studentName,string reportTitle,string className,int page = 1)
        {
            ViewBag.studentName = studentName;
            ViewBag.reportTitle = reportTitle;
            ViewBag.className = className;
            var studentReports = _studentReportService.Get(studentName,reportTitle,className);
            return View(studentReports.ToPagedList(page, 3));
        }


        // GET: StudentReports/Create
        public ActionResult Create()
        {
            PrepareSelectList();
            return View();
        }

        private void PrepareSelectList()
        {
            ViewBag.ClassSn = _selectListService.GetAllClassInfo();
        }

        // POST: StudentReports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Sn,StudentName,StudentNo,ReportTitle,UpdateTime,PdfPath,PptPath,ClassSn")] StudentReport studentReport, HttpPostedFileBase pdfFile, HttpPostedFileBase pptFile)
        {
            if (ModelState.IsValid)
            {
                studentReport.UpdateTime = DateTime.Now;
                if (pdfFile != null && pdfFile.ContentLength > 0)
                {
                    studentReport.PdfPath = SaveFile(pdfFile, studentReport.ClassSn.ToString());
                }

                if (pptFile != null && pptFile.ContentLength > 0)
                {
                    studentReport.PptPath = SaveFile(pptFile, studentReport.ClassSn.ToString());
                }

                _studentReportService.Add(studentReport);
                return RedirectToAction("Index");
            }
            PrepareSelectList();
            return View(studentReport);
        }

        private string SaveFile(HttpPostedFileBase file, string classSn)
        {
            var fileName = Path.GetFileName(file.FileName);
            var path = Server.MapPath($"~/Upload/StudentReports/{classSn}");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
            path = Path.Combine(path, fileName);
            file.SaveAs(path);
            fileName = $"{classSn}\\{Path.GetFileName(file.FileName)}";
            return fileName;
        }


        // GET: StudentReports/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var studentReport = _studentReportService.GetById(id.Value);
            if (studentReport == null)
            {
                return HttpNotFound();
            }
            PrepareSelectList();
            return View(studentReport);
        }

        // POST: StudentReports/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Sn,StudentName,StudentNo,ReportTitle,PdfPath,PptPath,ClassSn")] StudentReport studentReport, HttpPostedFileBase pdfFile, HttpPostedFileBase pptFile)
        {
            if (ModelState.IsValid)
            {
                studentReport.UpdateTime = DateTime.Now;
                string oldPdfPath = studentReport.PdfPath;
                string oldPptPath = studentReport.PptPath;
                if (pdfFile != null && pdfFile.ContentLength > 0)
                {
                    studentReport.PdfPath = SaveFile(pdfFile, studentReport.ClassSn.ToString());
                    DeleteFile(oldPdfPath);
                }

                if (pptFile != null && pptFile.ContentLength > 0)
                {
                    studentReport.PptPath = SaveFile(pptFile, studentReport.ClassSn.ToString());
                    DeleteFile(oldPptPath);
                }
                _studentReportService.Update(studentReport);

                return RedirectToAction("Index");
            }
            PrepareSelectList();
            return View(studentReport);
        }

        // GET: StudentReports/Delete/5
        public ActionResult Delete(int id)
        {
            var studentReport = _studentReportService.GetById(id);
            DeleteFile(studentReport.PdfPath);
            DeleteFile(studentReport.PptPath);
            _studentReportService.Delete(studentReport);
            return Redirect(Request.UrlReferrer?.ToString());
        }
        private void DeleteFile(string filePath)
        {
            var path = Server.MapPath($"~/Upload/StudentReports/{filePath}");
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
        }

    }
}

CitcWeb/Views/StudentReports/Create.cshtml
@model CitcWeb.Domain.StudentReport

@{
    ViewBag.Title = "新增專題";
}

<h2>新增專題</h2>

@using (Html.BeginForm("Create","StudentReports",FormMethod.Post,new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            姓名
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentName, new { htmlAttributes = new { @class = "form-control" ,@required="required"} })
                @Html.ValidationMessageFor(model => model.StudentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            學號
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentNo, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.StudentNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">

            <div class="col-md-10">
                題目
                @Html.EditorFor(model => model.ReportTitle, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.ReportTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            更新時間
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.UpdateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            班隊
            <div class="col-md-10">
                @Html.DropDownList("ClassSn", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClassSn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            專題檔案
           <label class="control-label col-md-2">選擇檔案</label>
            <div class="col-md-10">
                <input type="file" name="pdfFile">
            </div>
        </div>

        <div class="form-group">
            簡報檔案
            <label class="control-label col-md-2">選擇檔案</label>
            <div class="col-md-10">
                <input type="file" name="pptFile">
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回", "Index", null, new { @class = "btn btn-info" })
</div>

@section styles{
    <link href="~/Content/select2.min.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Scripts/select2.full.min.js"></script>
    <script src="~/Scripts/select2select.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
}

CitcWeb/Views/StudentReports/Edit.cshtml
@model CitcWeb.Domain.StudentReport

@{
    ViewBag.Title = "編輯專題";
}

<h2>編輯專題</h2>

@using (Html.BeginForm("Edit","StudentReports",FormMethod.Post,new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Sn)

    <div class="form-group">
        姓名
        <div class="col-md-10">
            @Html.EditorFor(model => model.StudentName, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
            @Html.ValidationMessageFor(model => model.StudentName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        學號
        <div class="col-md-10">
            @Html.EditorFor(model => model.StudentNo, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
            @Html.ValidationMessageFor(model => model.StudentNo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        題目
        <div class="col-md-10">
            @Html.EditorFor(model => model.ReportTitle, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
            @Html.ValidationMessageFor(model => model.ReportTitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        班隊名稱
        <div class="col-md-10">
            @Html.DropDownListFor(model=>model.ClassSn, null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ClassSn, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        專題檔案
        <div class="col-md-10">
            @Html.HiddenFor(model => model.PdfPath)
           <label class="control-label col-md-2">選擇檔案</label>
            <div class="col-md-10">
                <input type="file" name="pdfFile">
            </div>
        </div>
    </div>

    <div class="form-group">
        簡報檔案
        <div class="col-md-10">
            @Html.HiddenFor(model => model.PptPath)
           <label class="control-label col-md-2">選擇檔案</label>
            <div class="col-md-10">
                <input type="file" name="pptFile">
            </div>
        </div>
    </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="編輯" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回", "Index",null,new { @class="btn btn-info"})
</div>

@section styles{

    <link href="~/Content/select2.min.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Scripts/select2.full.min.js"></script>
    <script src="~/Scripts/select2select.js"></script>
}

CitcWeb/Views/StudentReports/Index.cshtml
@using PagedList.Mvc;
@using PagedList;
@model IEnumerable<CitcWeb.Domain.StudentReport>

@{
    ViewBag.Title = "學員生專題";
}

<h2 id="pageTitle">學員生專題 <i id="titleIcon" class="fa fa-toggle-down"></i></h2>

<div id="searchDiv" class="jumbotron">
    @using (Html.BeginForm("Index", "StudentReports", FormMethod.Post))
    {
        <div class="form-inline">
            <span>姓名：</span> @Html.TextBox("studentName", null, new { @class = "form-control" })
            <span>題目：</span> @Html.TextBox("reportTitle", null, new { @class = "form-control" })
            <span>班隊：</span> @Html.TextBox("className", null, new { @class = "form-control" })
            <input type="submit" value="搜尋" class="col- btn btn-primary offset-md-1" />
        </div>
    }
</div>
<p>
    @Html.ActionLink("新增", "Create", null, new { @class = "btn btn-success" })
</p>
@Html.PagedListPager((IPagedList)Model,x=>Url.Action("Index",new { studentName=ViewBag.studentName,reportTitle=ViewBag.reportTitle,className=ViewBag.className,page=x}))
<table class="table">
    <tr>
        <th>
            姓名
        </th>
        <th>
            學號
        </th>
        <th>
            題目
        </th>
        <th>
            更新時間
        </th>
        <th>
            班隊名稱
        </th>
        <th>
            專題檔案
        </th>
        <th>
            簡報檔案
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.StudentName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StudentNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReportTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UpdateTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClassInfo.ClassName)
        </td>
        <td>
            @if (!string.IsNullOrWhiteSpace(item.PdfPath)) { 
                <a href="~/Upload/StudentReports/@item.PdfPath"><i class="fa fa-download fa-3x"></i></a>
            }
        </td>
        <td>
            @if (!string.IsNullOrWhiteSpace(item.PptPath)) { 
                <a href="~/Upload/StudentReports/@item.PptPath"><i class="fa fa-download fa-3x"></i></a>
            }
        </td>
        <td>
                @Html.ActionLink("編輯", "Edit", new { id = item.Sn }, new { @class = "btn btn-info" })
                @Html.ActionLink("刪除", "Delete", new { id = item.Sn }, new { @class = "btn btn-danger", onclick = "return confirm('確定要刪除嗎?');" })
        </td>
    </tr>
}

</table>
@section styles{
    <link href="~/Content/searchPage.css" rel="stylesheet" />
    <link href="~/Content/table.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Scripts/searchPage.js"></script>
}