CitcWeb/Controllers/AnnualCoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CitcWeb.Domain;
using CitcWeb.Services.Interface;
using PagedList;

namespace CitcWeb.Controllers
{
    public class AnnualCoursesController : Controller
    {
        private readonly ICourseService _courseService;
        private readonly ISelectListService _selectListService;

        public AnnualCoursesController(ICourseService courseService, ISelectListService selectListService)
        {
            _courseService = courseService;
            _selectListService = selectListService;
        }

        // GET: AnnualCourses
        public ActionResult Index(int classSn,string courseName, int page=1)
        {
            ViewBag.classSn = classSn;
            ViewBag.courseName = courseName;
            return View(_courseService.GetAnnualCourse(classSn,courseName).ToPagedList(page,3));
        }

        // GET: AnnualCourses/Create
        public ActionResult Create(int classSn)
        {
            PrepareSelectList(classSn);
            return View(new AnnualCourse{ClassSn = classSn});
        }

        private void PrepareSelectList(int classSn)
        {
            ViewBag.ClassSn = _selectListService.GetClassInfo();
            ViewBag.CourseSn = _selectListService.GetCourse();
        }

        // POST: AnnualCourses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Sn,CourseSn,ClassSn,TotalHour")] AnnualCourse annualCourse)
        {
            if (ModelState.IsValid)
            {
                _courseService.AddAnnualCourse(annualCourse);
                return RedirectToAction("Index",new {classSn = annualCourse.ClassSn});
            }
            PrepareSelectList(annualCourse.ClassSn);
            return View(annualCourse);
        }

        // GET: AnnualCourses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var annualCourse = _courseService.GetAnnualCourseById(id.Value);
            if (annualCourse == null)
            {
                return HttpNotFound();
            }
            PrepareSelectList(annualCourse.ClassSn);
            return View(annualCourse);
        }

        // POST: AnnualCourses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Sn,CourseSn,ClassSn,TotalHour")] AnnualCourse annualCourse)
        {
            if (ModelState.IsValid)
            {
                _courseService.UpdateAnnualCourse(annualCourse);
                return RedirectToAction("Index",new {classSn = annualCourse.ClassSn});
            }
            PrepareSelectList(annualCourse.ClassSn);
            return View(annualCourse);
        }

        // GET: AnnualCourses/Delete/5
        public ActionResult Delete(int id)
        {
            _courseService.TryDeleteAnnualCourse(id);
            
            return Redirect(Request.UrlReferrer?.ToString());
        }

    }
}

CitcWeb/Controllers/ClassInfoController.cs
using System.Collections.Generic;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CitcWeb.Domain;
using CitcWeb.Models;
using CitcWeb.Models.Csv;
using CitcWeb.Services.Interface;
using PagedList;

namespace CitcWeb.Controllers
{
    public class ClassInfoController : Controller
    {
        private readonly IClassInfoService _classInfoService;

        public ClassInfoController(IClassInfoService classInfoService)
        {
            _classInfoService = classInfoService;
        }

        // GET: ClassInfoes
        public ActionResult Index(string className,int page=1)
        {
            ViewBag.className = className;
            IEnumerable<ClassInfo> classInfo;
            if (string.IsNullOrWhiteSpace(className))
            {
                classInfo = _classInfoService.Get();
            }
            else
            {
                classInfo = _classInfoService.Get(className);
            }

            return View(classInfo.ToPagedList(page, 3));
        }


        // GET: ClassInfoes/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "file")] HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                var csvReader = new CsvReader<ClassCsvModel>();
                var classInfo = csvReader.Read(file.InputStream, true);
                _classInfoService.Add(classInfo);
                return RedirectToAction("Index");
            }

            return View();
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var classInfo = _classInfoService.GetById(id.Value);
            if (classInfo == null)
            {
                return HttpNotFound();
            }
            return View(classInfo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Sn,ClassName,StartDate,EndDate")] ClassInfo classInfo)
        {
            if (ModelState.IsValid)
            {
                _classInfoService.Update(classInfo);
                return RedirectToAction("Index");
            }
            return View(classInfo);
        }

        public ActionResult Delete(int id)
        {
            _classInfoService.TryDelete(id);
            return Redirect(Request.UrlReferrer?.ToString());
        }
        public ActionResult Copy(int id)
        {
            _classInfoService.Copy(id);
            return Redirect(Request.UrlReferrer?.ToString());
        }

    }
}

CitcWeb/Views/ClassInfo/Create.cshtml
@model CitcWeb.Domain.ClassInfo

@{
    ViewBag.Title = "新增班隊";
}

<h2>新增班隊</h2>

@using (Html.BeginForm("Create","ClassInfo",FormMethod.Post,new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <label class="control-label col-md-2">選擇檔案</label>
        <div class="col-md-10">
            <input type="file" name="file">
        </div>
    </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增" class="btn btn-success" />
            </div>
        </div>
    </div>
}


@*@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            班隊名稱
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClassName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClassName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            開訓日期
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            結訓日期
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="新增" class="btn btn-success" />
        </div>
    </div>
</div>
}*@

<div>
    @Html.ActionLink("返回", "Index",null,new { @class="btn btn-info"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryUI")
    <script src="~/Scripts/datepickerSet.js"></script>
}

CitcWeb/Views/ClassInfo/Edit.cshtml
@model CitcWeb.Domain.ClassInfo

@{
    ViewBag.Title = "編輯班隊";
}

<h2>編輯班隊</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Sn)

        <div class="form-group">
            班隊名稱
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClassName, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.ClassName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            開訓日期
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            結訓日期
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="編輯" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回", "Index",null,new { @class="btn btn-info"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryUI")
    <script src="~/Scripts/datepickerSet.js"></script>
}

CitcWeb/Views/ClassInfo/Index.cshtml
@using PagedList.Mvc;
@using PagedList;
@model IEnumerable<CitcWeb.Domain.ClassInfo>

@{
    ViewBag.Title = "班隊資訊";
}

<h2 id="pageTitle">班隊資訊 <i id="titleIcon" class="fa fa-toggle-down"></i></h2>

<div id="searchDiv" class="jumbotron">
    @using (Html.BeginForm("Index", "ClassInfo", FormMethod.Post))
    {
        <div class="form-inline">
            <span>班隊名稱：</span> @Html.TextBox("className", null, new { @class = "form-control" })
            <input type="submit" value="搜尋" class="col- btn btn-primary offset-md-1" />
        </div>
    }
</div>
<p>
    @Html.ActionLink("新增", "Create",null, new { @class = "btn btn-success" })
    <a href="~/CsvImoport/班隊匯入範例.csv" class="btn btn-dark">匯入範例CSV檔</a>
</p>
@Html.PagedListPager((IPagedList)Model,x=>Url.Action("Index",new { page=x,className=ViewBag.className}))
<table class="table">
    <tr>
        <th>
            班隊名稱
        </th>
        <th>
            開訓日期
        </th>
        <th>
            結訓日期
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td style="max-width:unset">
            @Html.DisplayFor(modelItem => item.ClassName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td style="max-width:unset">
            @Html.ActionLink("課程維護", "Index","AnnualCourses", new { classSn = item.Sn }, new { @class = "btn btn-secondary" } )
            @Html.ActionLink("複製", "Copy", new { id = item.Sn }, new { @class = "btn btn-outline-dark", onclick = "return confirm('確定要複製嗎?');" } )
            @Html.ActionLink("編輯", "Edit", new { id = item.Sn }, new { @class = "btn btn-info" } )
            @Html.ActionLink("刪除", "Delete", new { id=item.Sn },new { @class="btn btn-danger", onclick = "return confirm('確定要刪除嗎?');" })
        </td>
    </tr>
}

</table>

@section styles{
    <link href="~/Content/searchPage.css" rel="stylesheet" />
    <link href="~/Content/table.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Scripts/searchPage.js"></script>
}