CitcWeb/Controllers/TeachersController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CitcWeb.Domain;
using CitcWeb.Models;
using CitcWeb.Models.Csv;
using CitcWeb.Services;
using CitcWeb.Services.Interface;
using PagedList;

namespace CitcWeb.Controllers
{
    public class TeachersController : Controller
    {
        private readonly ITeacherService _teacherService;

        public TeachersController(ITeacherService teacherService)
        {
            _teacherService = teacherService;
        }

        // GET: Teachers
        public ActionResult Index(string teacherName,int page=1)
        {
            ViewBag.teacherName = teacherName;
            IEnumerable<Teacher> teachers;
            if (string.IsNullOrWhiteSpace(teacherName))
            {
                teachers = _teacherService.Get();
            }
            else
            {
                teachers = _teacherService.Get(teacherName);
            }

            return View(teachers.ToPagedList(page, 3));
        }

        // GET: Teachers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "file")] HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                var csvReader = new CsvReader<TeacherCsvModel>();
                var teacherCsvModels = csvReader.Read(file.InputStream, true);
                _teacherService.Add(teacherCsvModels);
                
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var teacher = _teacherService.GetById(id.Value);
            if (teacher == null)
            {
                return HttpNotFound();
            }

            return View(teacher);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include = "Sn,IdNum,Name,County,PhoneNum,MilNum,Email,PayBureauNum,PayAccount,IsValid")]
            Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                _teacherService.Update(teacher);
                return RedirectToAction("Index");
            }

            return View(teacher);
        }

        // GET: Teachers/Delete/5
        public ActionResult Delete(int id)
        {
            _teacherService.TryDelete(id);
            return Redirect(Request.UrlReferrer?.ToString());
        }
        
    }
}

CitcWeb/Views/Teachers/Create.cshtml
@model CitcWeb.Domain.Teacher

@{
    ViewBag.Title = "新增教官";
}

<h2>新增教官</h2>


@using (Html.BeginForm("Create", "Teachers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="control-label col-md-2">選擇檔案</label>
            <div class="col-md-10">
                <input type="file" name="file">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回", "Index", null, new { @class = "btn btn-info" })
</div>

@section styles{

    <link href="~/Content/select2.min.css" rel="stylesheet" />
}
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/select2.full.min.js"></script>
    <script src="~/Scripts/select2select.js"></script>
}

CitcWeb/Views/Teachers/Edit.cshtml
@model CitcWeb.Domain.Teacher

@{
    ViewBag.Title = "編輯教官資訊";
}

<h2>編輯教官資訊</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Sn)

    <div class="form-group">
        身分證字號
        <div class="col-md-10">
            @Html.EditorFor(model => model.IdNum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IdNum, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        姓名
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        戶籍
        <div class="col-md-10">
            @Html.EditorFor(model => model.County, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.County, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        手機
        <div class="col-md-10">
            @Html.EditorFor(model => model.PhoneNum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PhoneNum, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        軍線
        <div class="col-md-10">
            @Html.EditorFor(model => model.MilNum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MilNum, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        連絡信箱
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        轉帳局號
        <div class="col-md-10">
            @Html.EditorFor(model => model.PayBureauNum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PayBureauNum, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        轉帳帳號
        <div class="col-md-10">
            @Html.EditorFor(model => model.PayAccount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PayAccount, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        是否可選
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsValid)
                @Html.ValidationMessageFor(model => model.IsValid, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="編輯" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回", "Index",null,new { @class="btn btn-info"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CitcWeb/Views/Teachers/Index.cshtml
@using PagedList.Mvc;
@using PagedList;
@model IEnumerable<CitcWeb.Domain.Teacher>

@{
    ViewBag.Title = "教官資訊";
}

<h2 id="pageTitle">教官資訊 <i id="titleIcon" class="fa fa-toggle-down"></i></h2>

<div id="searchDiv" class="jumbotron">
    @using (Html.BeginForm("Index", "Teachers", FormMethod.Post))
    {
        <div class="form-inline">
            <span>教官姓名：</span> @Html.TextBox("teacherName", null, new { @class = "form-control" })
            <input type="submit" value="搜尋" class="col- btn btn-primary offset-md-1" />
        </div>
    }
</div>
<p>
    @Html.ActionLink("新增", "Create", null, new { @class = "btn btn-success" })
    <a href="~/CsvImoport/教官匯入範例.csv" class="btn btn-dark">匯入範例CSV檔</a>
</p>

@Html.PagedListPager((IPagedList)Model,x=>Url.Action("Index",new { teacherName=ViewBag.teacherName,page=x}))
<table class="table">
    <tr>
        <th>
            身分證字號
        </th>
        <th>
            姓名
        </th>
        <th>
            戶籍
        </th>
        <th>
            手機
        </th>
        <th>
            軍線
        </th>
        <th>
            連絡信箱
        </th>
        <th>
            轉帳局號
        </th>
        <th>
            轉帳帳號
        </th>
        <th>
            是否可選
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.County)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MilNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PayBureauNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PayAccount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsValid)
            </td>
            <td>
                @Html.ActionLink("編輯", "Edit", new { id = item.Sn }, new { @class = "btn btn-info" })
                @Html.ActionLink("刪除", "Delete", new { id = item.Sn }, new { @class = "btn btn-danger", onclick = "return confirm('確定要刪除嗎?');" })
            </td>
        </tr>
    }

</table>

@section styles{
    <link href="~/Content/searchPage.css" rel="stylesheet" />
    <link href="~/Content/table.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Scripts/searchPage.js"></script>
}